#!/usr/bin/env python3
"""_gen_text.py - parse rawgl staticres.cpp -> tools/aw_text.py (font + strings).
One-shot generator; keep _staticres.cpp around to regenerate. Run from project root."""
import re, io, os

HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, '_staticres.cpp'), 'r', encoding='utf-8', errors='replace').read()

# --- FONT: 768 bytes between _font[] = { ... }; ---
m = re.search(r'_font\[\]\s*=\s*\{(.*?)\};', src, re.S)
font_bytes = [int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{2})', m.group(1))]
assert len(font_bytes) == 768, len(font_bytes)

# --- English strings: { 0xID, "..." } ; keep FIRST occurrence (rawgl findString) ---
m = re.search(r'_stringsTableEng\[\]\s*=\s*\{(.*?)\};', src, re.S)
ent = re.findall(r'\{\s*0x([0-9A-Fa-f]+)\s*,\s*"((?:[^"\\]|\\.)*)"\s*\}', m.group(1))


def unesc(s):
    out = []
    i = 0
    while i < len(s):
        c = s[i]
        if c == '\\' and i + 1 < len(s):
            n = s[i + 1]
            out.append({'n': '\n', 't': '\t', '"': '"', '\\': '\\'}.get(n, n))
            i += 2
        else:
            out.append(c)
            i += 1
    return ''.join(out)


strings = {}
for hid, s in ent:
    i = int(hid, 16)
    if i not in strings:          # first wins
        strings[i] = unesc(s)

out = io.StringIO()
out.write('#!/usr/bin/env python3\n')
out.write('"""aw_text.py - AW static font + English string table (from rawgl staticres.cpp).\n')
out.write('Auto-generated by _gen_text.py; do not edit by hand. FONT = 96 glyphs x 8 bytes\n')
out.write('(ASCII 0x20-0x7F, MSB-first). STRINGS = {id: text}. draw_string() renders glyphs\n')
out.write('into a page exactly like AW drawString/drawChar, so aw_sim (oracle) and aw_play\n')
out.write('(replay) agree byte-for-byte."""\n\n')
out.write('FONT = bytes([\n')
for r in range(0, 768, 16):
    out.write('    ' + ', '.join('0x%02X' % b for b in font_bytes[r:r + 16]) + ',\n')
out.write('])\n\n')
out.write('STRINGS = {\n')
for i in sorted(strings):
    out.write('    0x%03X: %r,\n' % (i, strings[i]))
out.write('}\n\n')
out.write('''
def draw_string(page, width, str_id, x, y, color):
    """Render STRINGS[str_id] into `page` (1 byte/pixel, `width` px/row) at char
    column x (each char is 8 px wide), pixel row y, solid `color`. Mirrors AW
    drawString: a newline advances y by 8 and resets x to the start column. Glyph
    bit order is MSB-first (0x80>>i). Out-of-range pixels are clipped."""
    s = STRINGS.get(str_id)
    if s is None:
        return
    h = len(page) // width
    cx = x
    for ch in s:
        if ch == chr(10):
            y += 8
            cx = x
            continue
        oc = ord(ch)
        if 0x20 <= oc <= 0x7F:
            g = (oc - 0x20) * 8
            for j in range(8):
                row = FONT[g + j]
                py = y + j
                if 0 <= py < h:
                    base = py * width + cx * 8
                    for i in range(8):
                        if row & (0x80 >> i):
                            px = cx * 8 + i
                            if 0 <= px < width:
                                page[base + i] = color
        cx += 1
''')
open(os.path.join(HERE, 'aw_text.py'), 'w', encoding='utf-8').write(out.getvalue())
print('wrote tools/aw_text.py : FONT=%d bytes, STRINGS=%d ids' % (len(font_bytes), len(strings)))
