#!/usr/bin/env python3
"""gen_intro_sfx8.py - pack the intro SFX as 8-bit samples for the COVOX player.

Prototype companion to gen_intro_sfx.py (the 4-bit POKEY build). Instead of
4-bit POKEY nibbles this emits FULL 8-bit unsigned samples (1 byte = 1 sample),
matched 1:1 in COUNT to the 4-bit build so playback timing/pitch are identical:
the IRQ rate is unchanged, only the amplitude resolution goes 4-bit -> 8-bit.

Per sound:
  N8 = 2 * len(out/audio/pokey/sfx_XX.bin)     # = nibble count of the 4-bit blob
  source = out/audio/sfx_XX.wav                 # 8-bit unsigned mono (full quality)
  linear-resample source -> exactly N8 samples, keep 8-bit unsigned.

The 8-bit blob is ~2x bigger than the 4-bit one (41270 vs 20635 B) so it no
longer fits the 2 free banks $0E-$0F. It is placed at SOUND_BASE8 = $044000
(banks $11,$12,$13 -- the unused gap between the control bank $10 and the poly
banks $14+; the GAME build already treats $11-$13 as free sound VRAM).

Emits:
  out/intro_sfx8.bin       the concatenated 8-bit blob (streamed to VRAM)
  src/aw_sfx_tables8.inc    per-sound {bank, window, len} tables (same symbols)
"""
import os, sys, wave

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
AUD = os.path.join(ROOT, 'out', 'audio')
PK = os.path.join(AUD, 'pokey')
OUT = os.path.join(ROOT, 'out')

SOUND_BASE8 = 0x044000          # VRAM byte address of the first sample (bank $11, win $4000)
SOUND_BANK0 = SOUND_BASE8 >> 14 # $11
POLY_BANK0 = 0x14              # first poly bank -> the 8-bit blob must stop before it

# same resId order as gen_intro_sfx.py (defines the sfx index 0..N-1)
RESIDS = [0x03, 0x05, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E,
          0x0F, 0x2C, 0x33, 0x36, 0x3C, 0x3F, 0x40, 0x41]


def bankwin(abs_addr):
    bank = 0x80 | (abs_addr >> 14)
    win = 0x4000 | (abs_addr & 0x3FFF)
    return bank, win & 0xFF, win >> 8


def read_wav_u8(path):
    """Return a list of unsigned-8-bit samples (mono) from a WAV (8 or 16 bit)."""
    with wave.open(path, 'rb') as w:
        nch, sw, _, n = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
        raw = w.readframes(n)
    if sw == 1:                                  # 8-bit unsigned PCM
        samples = list(raw)
        if nch > 1:
            samples = samples[::nch]
        return samples
    if sw == 2:                                  # 16-bit signed PCM -> u8
        out = []
        for i in range(0, len(raw), 2 * nch):
            lo, hi = raw[i], raw[i + 1]
            v = lo | (hi << 8)
            if v & 0x8000:
                v -= 0x10000
            out.append((v >> 8) + 128)           # signed16 -> unsigned8
        return out
    sys.exit(f"unsupported sample width {sw} in {path}")


def resample(src, n_out):
    """Linear-resample src (list of u8) to exactly n_out u8 samples."""
    n_in = len(src)
    if n_in == 0:
        return [128] * n_out
    if n_in == 1:
        return [src[0]] * n_out
    if n_out == 1:
        return [src[0]]
    out = []
    scale = (n_in - 1) / (n_out - 1)
    for j in range(n_out):
        x = j * scale
        i = int(x)
        if i >= n_in - 1:
            out.append(src[-1])
        else:
            f = x - i
            out.append(int(round(src[i] * (1.0 - f) + src[i + 1] * f)) & 0xFF)
    return out


def main():
    blob = bytearray()
    starts, lens = [], []
    for rid in RESIDS:
        pk = os.path.join(PK, f'sfx_{rid:02x}.bin')
        n8 = 2 * os.path.getsize(pk)             # 1:1 with the 4-bit nibble count
        src = read_wav_u8(os.path.join(AUD, f'sfx_{rid:02x}.wav'))
        data = bytes(resample(src, n8))
        starts.append(SOUND_BASE8 + len(blob))
        blob += data
        lens.append(n8)

    nbanks = (len(blob) + 0x3FFF) >> 14
    if SOUND_BANK0 + nbanks > POLY_BANK0:
        sys.exit(f"ERROR: 8-bit sfx blob {len(blob)}B needs {nbanks} banks from "
                 f"${SOUND_BANK0:02X} -> overruns poly bank ${POLY_BANK0:02X}. "
                 f"Trim sounds or relocate.")

    os.makedirs(OUT, exist_ok=True)
    open(os.path.join(OUT, 'intro_sfx8.bin'), 'wb').write(blob)

    sb = [bankwin(a) for a in starts]
    L = ['; auto-generated by tools/gen_intro_sfx8.py - DO NOT EDIT',
         f'; {len(RESIDS)} intro SFX, {len(blob)} bytes (8-bit COVOX) in VRAM '
         f'${SOUND_BASE8:06X} (banks ${SOUND_BANK0:02X}..${SOUND_BANK0+nbanks-1:02X})',
         f'SFX_COUNT = {len(RESIDS)}',
         'sfx_bank    dta ' + ','.join(f'${b:02X}' for b, _, _ in sb),
         'sfx_winlo   dta ' + ','.join(f'${l:02X}' for _, l, _ in sb),
         'sfx_winhi   dta ' + ','.join(f'${h:02X}' for _, _, h in sb),
         '; byte lengths (= sample counts; player counts a NEGATED copy up to 0)',
         'sfx_lenlo   dta ' + ','.join(f'${l & 0xFF:02X}' for l in lens),
         'sfx_lenhi   dta ' + ','.join(f'${l >> 8:02X}' for l in lens)]
    open(os.path.join(ROOT, 'src', 'aw_sfx_tables8.inc'), 'w').write('\n'.join(L) + '\n')

    print(f"intro SFX (8-bit): {len(RESIDS)} sounds, {len(blob)} bytes -> {nbanks} "
          f"VRAM bank(s) ${SOUND_BANK0:02X}..${SOUND_BANK0+nbanks-1:02X}")
    print(f"  4-bit was {len(blob)//2} B in 2 banks; 8-bit is {len(blob)} B in {nbanks} banks")
    print(f"  out/intro_sfx8.bin, src/aw_sfx_tables8.inc")


if __name__ == '__main__':
    main()
