#!/usr/bin/env python3
"""gen_intro_sfx.py - pack the intro's sound effects for the VRAM POKEY player.

Reads the 4-bit POKEY-packed sounds (out/audio/pokey/sfx_XX.bin, produced by
doom2d's wav2pokey.py from the extracted AW intro sounds) for the resources the
intro actually plays, concatenates them into one blob placed in VBXE VRAM at
SOUND_BASE ($038000, the free banks $0E-$0F between page 3 and the control bank),
and emits:
  out/intro_sfx.bin        the concatenated 4-bit blob (streamed to VRAM by aw_data.asm)
  src/aw_sfx_tables.inc     per-sound start/end MEMAC-B {bank, window} address tables
  out/intro_sfx_map.json    resId -> sfx index map (read by aw_playlist.py)

VRAM address -> MEMAC-B form:  bank = $80 | (abs>>14) ;  window = $4000 | (abs & $3FFF).
The 6502 IRQ advances the window byte by byte and steps to the next bank at $8000.
"""
import os, sys, json

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PK = os.path.join(ROOT, 'out', 'audio', 'pokey')
OUT = os.path.join(ROOT, 'out')

SOUND_BASE = 0x038000          # VRAM byte address of the first sample (bank $0E, win $4000)
SOUND_BANK0 = SOUND_BASE >> 14 # $0E

# AW resource ids the intro plays (from the op_sound trace; 0x34 is an empty
# placeholder so it is omitted). Order here defines the sfx index 0..N-1.
RESIDS = [0x03, 0x05, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E,
          0x0F, 0x2C, 0x33, 0x36, 0x3C, 0x3F, 0x40, 0x41]


def bankwin(abs_addr):
    """VRAM byte address -> (MEMAC-B bank value, window lo, window hi)."""
    bank = 0x80 | (abs_addr >> 14)
    win = 0x4000 | (abs_addr & 0x3FFF)
    return bank, win & 0xFF, win >> 8


def main():
    blob = bytearray()
    starts, ends = [], []
    for rid in RESIDS:
        p = os.path.join(PK, f'sfx_{rid:02x}.bin')
        data = open(p, 'rb').read()
        starts.append(SOUND_BASE + len(blob))
        blob += data
        ends.append(SOUND_BASE + len(blob))

    os.makedirs(OUT, exist_ok=True)
    open(os.path.join(OUT, 'intro_sfx.bin'), 'wb').write(blob)

    nbanks = (len(blob) + 0x3FFF) >> 14
    if SOUND_BANK0 + nbanks > 0x10:
        sys.exit(f"ERROR: sfx blob {len(blob)}B needs {nbanks} banks from ${SOUND_BANK0:02X}"
                 f" -> would overrun the control bank $10. Move SOUND_BASE or trim sounds.")

    # start/end bank+window tables (player stops when ptr == end)
    sb = [bankwin(a) for a in starts]
    eb = [bankwin(a) for a in ends]
    lens = [e - s for s, e in zip(starts, ends)]
    L = ['; auto-generated by tools/gen_intro_sfx.py - DO NOT EDIT',
         f'; {len(RESIDS)} intro SFX, {len(blob)} bytes (4-bit) in VRAM ${SOUND_BASE:06X}'
         f' (banks ${SOUND_BANK0:02X}..${SOUND_BANK0+nbanks-1:02X})',
         f'SFX_COUNT = {len(RESIDS)}',
         'sfx_bank    dta ' + ','.join(f'${b:02X}' for b, _, _ in sb),
         'sfx_winlo   dta ' + ','.join(f'${l:02X}' for _, l, _ in sb),
         'sfx_winhi   dta ' + ','.join(f'${h:02X}' for _, _, h in sb),
         '; byte lengths (the player counts a NEGATED copy up to 0; replaces the',
         '; old 3-way end-pointer compare -- see aw_sound.asm)',
         'sfx_lenlo   dta ' + ','.join(f'${l & 0xFF:02X}' for l in lens),
         'sfx_lenhi   dta ' + ','.join(f'${l >> 8:02X}' for l in lens)]
    open(os.path.join(ROOT, 'src', 'aw_sfx_tables.inc'), 'w').write('\n'.join(L) + '\n')

    json.dump({str(rid): i for i, rid in enumerate(RESIDS)},
              open(os.path.join(OUT, 'intro_sfx_map.json'), 'w'))

    print(f"intro SFX: {len(RESIDS)} sounds, {len(blob)} bytes -> {nbanks} VRAM bank(s) "
          f"${SOUND_BANK0:02X}..${SOUND_BANK0+nbanks-1:02X}")
    print(f"  out/intro_sfx.bin, src/aw_sfx_tables.inc, out/intro_sfx_map.json")
    rem = len(blob) - 0x4000
    print(f"  bank $0E chunk: $0000..$4000 (16384 B); bank $0F chunk: $4000..{len(blob)} ({rem} B)")


if __name__ == '__main__':
    main()
