#!/usr/bin/env python3
"""gen_game_text.py - emit src_game/game_text_data.inc : the AW 8x8 font + the
FULL AW string table, for the GAME's op_drawstring (bytecode opcode 0x12).

The intro generator (gen_text_data.py) only ships the IDs the flattened intro
playlist references. The GAME runs the real bytecode and can call drawString with
any id (death/ACCESS CODE screens, lab dialogue, ...), so this ships ALL 139
strings (~2.2 KB). Same label names as aw_text_data.inc (aw_font / aw_id_lo..hi /
aw_str_lo..hi / aw_strbytes / aw_nstr) -- the game includes only THIS file, so no
clash with the intro's table. Run from the project root."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import aw_text

INC = os.path.join(PROJ, 'src_game', 'game_text_data.inc')


def encode(s):
    out = bytearray()
    for ch in s:
        out.append(0x0A if ch == '\n' else (ord(ch) & 0xFF))
    out.append(0x00)
    return bytes(out)


def dta_block(label, data, comment=''):
    out = [f'{label}' + (f'    ; {comment}' if comment else '')]
    for r in range(0, len(data), 16):
        out.append('    dta ' + ','.join('$%02X' % b for b in data[r:r + 16]))
    return '\n'.join(out)


def main():
    ids = sorted(aw_text.STRINGS.keys())
    blob = bytearray()
    offs = []
    for sid in ids:
        offs.append(len(blob))
        blob += encode(aw_text.STRINGS[sid])
    assert len(blob) < 0x10000, 'string blob > 64 KB'

    L = ['; ==========================================================================',
         '; game_text_data.inc - AUTO-GENERATED by tools/gen_game_text.py. Do not edit.',
         '; AW 8x8 font (96 glyphs, ASCII $20-$7F) + the FULL AW string table (game).',
         '; ==========================================================================',
         'aw_nstr equ %d' % len(ids), '',
         dta_block('aw_font', aw_text.FONT, '96 glyphs x 8 bytes, MSB-first'), '',
         dta_block('aw_id_lo', [s & 0xFF for s in ids], 'string id, low byte'),
         dta_block('aw_id_hi', [(s >> 8) & 0xFF for s in ids], 'string id, high byte'),
         dta_block('aw_str_lo', [o & 0xFF for o in offs], 'offset into aw_strbytes, low'),
         dta_block('aw_str_hi', [(o >> 8) & 0xFF for o in offs], 'offset, high'), '',
         dta_block('aw_strbytes', blob, '%d bytes, each string $00-terminated' % len(blob)), '']
    open(INC, 'w', encoding='ascii').write('\n'.join(L) + '\n')
    total = 768 + len(ids) * 4 + len(blob)
    print(f'wrote {INC}')
    print(f'  ids={len(ids)}  font=768  table={len(ids)*4}  strbytes={len(blob)}  total={total} bytes')


if __name__ == '__main__':
    main()
