#!/usr/bin/env python3
"""gen_text_data.py - emit src/aw_text_data.inc : the AW font + the intro's
string table, for the 6502 op_drawtext (playlist opcode 0x07).

Only the string IDs the playlist actually references (scanned from
out/intro_playlist.bin) are included, so the table stays tiny (~1.8 KB). The
6502 looks a strId up by linear scan of aw_id_lo/hi, then renders aw_strbytes
(null-terminated; newline = $0A) through the 8x8 font with fill_span.

Run from the project root after aw_playlist.py."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import aw_text

PL = os.path.join(PROJ, 'out', 'intro_playlist.bin')
INC = os.path.join(PROJ, 'src', 'aw_text_data.inc')

# playlist opcode operand lengths (bytes AFTER the opcode), to walk the stream
OPLEN = {0x01: 1, 0x02: 1, 0x03: 2, 0x04: 2, 0x05: 8, 0x06: 2, 0x07: 5}


def used_ids(pl):
    i, L, used = 0, len(pl), []
    seen = set()
    while i < L:
        op = pl[i]; i += 1
        if op == 0x00:
            break
        if op == 0x07:
            sid = pl[i] | (pl[i + 1] << 8)
            if sid not in seen:
                seen.add(sid); used.append(sid)
        i += OPLEN.get(op, 0)
    return sorted(used)


def encode(s):
    """AW string -> 6502 bytes: newline -> $0A, others latin-1, then $00 term."""
    out = bytearray()
    for ch in s:
        out.append(0x0A if ch == '\n' else (ord(ch) & 0xFF))
    out.append(0x00)
    return bytes(out)


def dta_block(label, data, comment=''):
    out = [f'{label}' + (f'    ; {comment}' if comment else '')]
    for r in range(0, len(data), 16):
        out.append('    dta ' + ','.join('$%02X' % b for b in data[r:r + 16]))
    return '\n'.join(out)


def main():
    pl = open(PL, 'rb').read()
    ids = used_ids(pl)

    # build the concatenated string blob + per-id offset
    blob = bytearray()
    offs = []
    for sid in ids:
        offs.append(len(blob))
        blob += encode(aw_text.STRINGS.get(sid, ''))
    assert len(blob) < 0x10000

    L = []
    L.append('; ==========================================================================')
    L.append('; aw_text_data.inc - AUTO-GENERATED by tools/gen_text_data.py. Do not edit.')
    L.append('; AW 8x8 font (96 glyphs, ASCII $20-$7F) + the intro string table.')
    L.append('; ==========================================================================')
    L.append('aw_nstr equ %d' % len(ids))
    L.append('')
    L.append(dta_block('aw_font', aw_text.FONT, '96 glyphs x 8 bytes, MSB-first'))
    L.append('')
    L.append(dta_block('aw_id_lo', [s & 0xFF for s in ids], 'string id, low byte'))
    L.append(dta_block('aw_id_hi', [(s >> 8) & 0xFF for s in ids], 'string id, high byte'))
    L.append(dta_block('aw_str_lo', [o & 0xFF for o in offs], 'offset into aw_strbytes, low'))
    L.append(dta_block('aw_str_hi', [(o >> 8) & 0xFF for o in offs], 'offset, high'))
    L.append('')
    L.append(dta_block('aw_strbytes', blob, '%d bytes, each string $00-terminated' % len(blob)))
    L.append('')
    open(INC, 'w', encoding='ascii').write('\n'.join(L) + '\n')

    total = 768 + len(ids) * 4 + len(blob)
    print(f'wrote {INC}')
    print(f'  ids={len(ids)}  font=768  table={len(ids)*4}  strbytes={len(blob)}  total={total} bytes')


if __name__ == '__main__':
    main()
