#!/usr/bin/env python3
"""gen_voltab8.py - the LINEAR volume curves used by the COVOX output mode.

The POKEY build scales SFX nibbles through `voltab` (gen_intro_sfx.py): 16 rows
x 16 nibbles, each entry pre-ORed with $10 for AUDC volume-only mode, i.e. the
values stay in POKEY's 4-bit volume domain and inherit its non-linearity.

A covox is a plain R-2R ladder, so its curves live in a 7-bit LINEAR domain:

    row L (0..15)  ->  gain g = min(63, 4L+3) / 63      (same rows as voltab:
                                                         row L covers vols 4L..4L+3)
    entry n (0..15) ->  v = round(64 + (n-8) * 8 * g)   clamped to 0..127

64 is mid rail for ONE voice: the mix tail in aw_sound.asm adds the SFX level
to the music nibble scaled <<3 (also 0..120, mid 64), so two silent voices sum
to exactly $80 -- the covox centre. Row 15 (g = 1.0) is exactly n*8.

This table depends on nothing but the arithmetic above, so unlike the SFX blob
it does NOT need orig/ and is generated once:

    python tools/gen_voltab8.py   ->   src/aw_voltab8.inc
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def main():
    rows = []
    for L in range(16):
        g = min(63, 4 * L + 3) / 63.0
        rows.append([max(0, min(127, int(round(64 + (n - 8) * 8 * g))))
                     for n in range(16)])

    out = ['; auto-generated by tools/gen_voltab8.py - DO NOT EDIT',
           '; 16 LINEAR volume curves x 16 nibbles for the COVOX mix (0..127,',
           '; silence = 64). snd_play copies row vol>>2 to snd_vt exactly like the',
           '; POKEY voltab -- snd_go_covox only repoints its base (vb1/vb2).',
           'voltab8']
    for row in rows:
        out.append('        dta ' + ','.join(f'${v:02X}' for v in row))

    path = os.path.join(ROOT, 'src', 'aw_voltab8.inc')
    open(path, 'w').write('\n'.join(out) + '\n')
    print(f'{path}: 16 rows x 16 = 256 B '
          f'(row0 {rows[0][0]}..{rows[0][15]}, row15 {rows[15][0]}..{rows[15][15]})')


if __name__ == '__main__':
    main()
